language: objective-c
osx_image: mavericks
notifications:
  email: false
rvm:
- 2.1.1
env:
  global:
  - secure: hd4j5sZCz/lLyRydPcepSb3nYBH2JvetTlVCOcCX0WC2N2m5NTWPKm2n8slV+dJ5my9SmX+GiYXOc+DHAFtzBPRhvm145Bgep3HxSknBr3+dz0OCG2vVyRvqIsRAawVCkrytjXC2dDsk+Gbp/2px/M1NKDV6PK5oEZYBdP8oPxM=
  - secure: YWix/tuImrQHynX9u+TKN9dxwkQqc2v/3MzEsvHVqom2/b6Twh0xEj3rPqlTSSRqVwOm6lOKFDIvvz+bdSBaAZbgFukTYIF4hqnOIXxjsgjy4hLji7hoT3FEtuPMMIlWTPY1rhk80RNJBJ0BJ6eNjKDhI7wMaQudJ0ThwH91Mwo=
  matrix:
  - CI_CONFIG=unit
  - CI_CONFIG=build
before_script:
- gem install --no-rdoc --no-ri appium_doc_lint
- "./ci/install-node.sh"
- "./ci/show-env.sh"
- npm install -g jshint grunt-cli
- npm install
- "./ci/before_script_extra.sh"
script:
- "./ci/script.sh"
