language: objective-c
osx_image: mavericks
notifications:
  email: false
rvm:
- 2.1.1
branches:
  only:
  - master
git:
  submodules: false
env:
  global:
  - SAUCE_REST_ROOT=https://saucelabs.com/rest/v1
  - APPIUM_HOST='ondemand.saucelabs.com'
  - APPIUM_PORT=80
  - SAUCE_USERNAME=sebv
  - secure: W0lWyFjhSce3IbaxBVEFOqWt9er1obwDxaiBT2HqsejsViorQh7N/LRdcEj+bUFqJJr+WDZNPMoBe+hv5BZcroeT03bn1QVNVo0DR3uU9KH6wRnWqumnP46BYEqhzn3h1ayGUsBtIG+ZXIbLytOM4Cbjbj8VshI0Y88N3B0P0mw=
  - secure: LD8NtDTcDHqnpWtBV3RSbvrv8a04sRsRwwg02eawidSXFRSbSnF5iMLooiLVEA9nquji2xfvhlS5ctNEKWgG+mTqS8APxdtMceerF6Mlg3tI1D3jTBlsQO1wOSIx9qFNZE4GGO/kB0iTvZrQ7JmRPZC3NQB/q0CLib/gTk6l8ZA=
  matrix:
  - CI_CONFIG=unit
  - CI_CONFIG=build_ios
  - CI_CONFIG=build_android
  - CI_CONFIG=build_selendroid
  - CI_CONFIG=build_gappium
before_script:
- gem install --no-rdoc --no-ri appium_doc_lint
- "./ci/git-config.sh"
- "./ci/installers/install-node.sh"
- "echo Node.js version: `node -v`"
- npm install -g jshint grunt-cli mocha
- npm install
- "./ci/before_script_extra.sh"
script:
- "./ci/script.sh"

